swagger: '2.0'
host: p6t3dy354h.execute-api.us-east-1.amazonaws.com
basePath: /prod
schemes:
  - https
info:
  version: '0.0.1'
  title: 'Trunkshow API'
  description: 'For Hackathon Oct 2019'
paths:
  '/trunkshows/{trunkshow_id}/backstage/comments/{comment_id}':
    put:
      description: Publish a new backstage comment
      produces:
        - application/json
      parameters:
        - name: comment_id
          in: path
          required: true
          type: string
          format: uuid
        - name: trunkshow_id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Image created.
          schema:
            $ref: '#/definitions/BackstageItem'
  '/trunkshows/{trunkshow_id}/backstage/images/{image_id}':
    put:
      description: Publish a new backstage image
      produces:
        - application/json
      parameters:
        - name: image_id
          in: path
          required: true
          type: string
          format: uuid
        - name: trunkshow_id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Image created.
          schema:
            $ref: '#/definitions/BackstageItem'
  '/trunkshows/{trunkshow_id}/backstage/items':
    get:
      description: Gets an array of backstage items for a trunkshow
      produces:
        - application/json
      parameters:
        - name: image_id
          in: path
          required: true
          type: string
          format: uuid
        - name: product_id
          in: query
          required: false
          type: integer
          format: int32
        - name: trunkshow_id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Image created.
          schema:
            $ref: '#/definitions/BackstageItems'
definitions:
  BackstageItem:
    type: object
    required:
      - id
      - trunkshow_id
    properties:
      comment:
        type: string
      id:
        type: string
        format: uuid
      image_url:
        type: string
      product_id:
        type: integer
        format: int32
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
      trunkshow_id:
        type: integer
        format: int32
  BackstageItems:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/BackstageItem'
  BackstageCommentForm:
    type: object
    required:
      - comment
    properties:
      comment:
        type: string
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
  BackstageImageForm:
    type: object
    required:
      - image_url
    properties:
      comment:
        type: string
      image_url:
        type: string
      product_id:
        type: integer
        format: int32
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
  Tag:
    type: object
    properties:
      key:
        type: string
      value:
        type: string