//
// BackstageItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct BackstageItem: Codable {


    public var comment: String?

    public var _id: UUID

    public var imageUrl: String?

    public var productId: Int?

    public var tags: [String]?

    public var trunkshowId: Int
    public init(comment: String?, _id: UUID, imageUrl: String?, productId: Int?, tags: [String]?, trunkshowId: Int) { 
        self.comment = comment
        self._id = _id
        self.imageUrl = imageUrl
        self.productId = productId
        self.tags = tags
        self.trunkshowId = trunkshowId
    }
    public enum CodingKeys: String, CodingKey { 
        case comment
        case _id = "id"
        case imageUrl = "image_url"
        case productId = "product_id"
        case tags
        case trunkshowId = "trunkshow_id"
    }

}
