//
// BackstageItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct BackstageItems: Codable {


    public var items: [BackstageItem]
    public init(items: [BackstageItem]) { 
        self.items = items
    }

}
