//
// BackstageImageForm.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct BackstageImageForm: Codable {


    public var comment: String?

    public var imageUrl: String

    public var productId: Int?

    public var tags: [String]?
    public init(comment: String?, imageUrl: String, productId: Int?, tags: [String]?) { 
        self.comment = comment
        self.imageUrl = imageUrl
        self.productId = productId
        self.tags = tags
    }
    public enum CodingKeys: String, CodingKey { 
        case comment
        case imageUrl = "image_url"
        case productId = "product_id"
        case tags
    }

}
